version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - TG_BOT_USERNAME=${TG_BOT_USERNAME}
      - ALIVE_NAME=${ALIVE_NAME}
      - STRING_SESSION=${STRING_SESSION}
